Add liborc manually, since we can't link to the one on Heroku
stack:
```
LoadError: Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': liborc-0.4.so.0: cannot open shared object file: No such file or directory.
```